import mongoose from "mongoose";

const matchSchema = new mongoose.Schema(
    {
        match_id: { type: Number, unique: true },
        title: String,
        short_title: String,
        subtitle: String,
        match_number: String,
        format: Number,
        format_str: String,
        status: Number,
        status_str: String,
        status_note: String,
        verified: String,
        pre_squad: String,
        odds_available: String,
        game_state: Number,
        game_state_str: String,
        domestic: String,
        competition: {
            cid: { type: Number },
            title: { type: String },
            abbr: { type: String },
            type: { type: String },
            category: { type: String },
            match_format: { type: String },
            season: { type: String },
            status: { type: String },
            datestart: { type: String },
            dateend: { type: String },
            country: { type: String },
            total_matches: { type: String },
            total_rounds: { type: String },
            total_teams: { type: String },
        },
        teama: {
            team_id: Number,
            name: String,
            short_name: String,
            logo_url: String,
        },
        teamb: {
            team_id: Number,
            name: String,
            short_name: String,
            logo_url: String,
        },
        date_start: String,
        date_end: String,
        timestamp_start: Number,
        timestamp_end: Number,
        date_start_ist: String,
        date_end_ist: String,
        venue: {
            venue_id: String,
            name: String,
            location: String,
            country: String,
            timezone: String,
        },
        umpires: String,
        referee: String,
        equation: String,
        live: String,
        result: String,
        result_type: String,
        win_margin: String,
        winning_team_id: Number,
        commentary: Number,
        wagon: Number,
        latest_inning_number: Number,
        presquad_time: String,
        verify_time: String,
        match_dls_affected: String,
        day: String,
        session: String,
        weather: {
            weather: String,
            weather_desc: String,
            temp: Number,
            humidity: Number,
            visibility: Number,
            wind_speed: String,
            clouds: Number,
        },
        pitch: {
            pitch_condition: String,
            batting_condition: String,
            pace_bowling_condition: String,
            spine_bowling_condition: String,
        },
        toss: {
            winner: Number,
            decision: Number,
        },
    },
    { timestamps: true }
);

export const Match = mongoose.model("Match", matchSchema);
